services:
  - type: web
    name: magekt-profile
    env: static
    staticPublishPath: .
    buildCommand: ""
    startCommand: ""
    routes:
      - type: rewrite
        source: /
        destination: /Index.html
